// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/message.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message represents a CloudEvent as defined by the CloudEvents spec v1.0.2.
// See: https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/spec.md
type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// REQUIRED: Identifies the event. source + id must be unique per distinct event.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// REQUIRED: Identifies the context in which the event happened (URI-reference).
	Source string `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	// REQUIRED: The version of the CloudEvents specification used. Must be "1.0".
	Specversion string `protobuf:"bytes,3,opt,name=specversion,proto3" json:"specversion,omitempty"`
	// REQUIRED: Describes the type of event related to the originating occurrence.
	Type string `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	// OPTIONAL: Content type of the data value (RFC 2046 media type).
	Datacontenttype *string `protobuf:"bytes,5,opt,name=datacontenttype,proto3,oneof" json:"datacontenttype,omitempty"`
	// OPTIONAL: URI identifying the schema that data adheres to.
	Dataschema *string `protobuf:"bytes,6,opt,name=dataschema,proto3,oneof" json:"dataschema,omitempty"`
	// OPTIONAL: Describes the subject of the event in the context of the event producer.
	Subject *string `protobuf:"bytes,7,opt,name=subject,proto3,oneof" json:"subject,omitempty"`
	// OPTIONAL: Timestamp of when the occurrence happened (RFC 3339).
	Time *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=time,proto3,oneof" json:"time,omitempty"`
	// OPTIONAL: Domain-specific event payload.
	Data []byte `protobuf:"bytes,9,opt,name=data,proto3,oneof" json:"data,omitempty"`
	// OPTIONAL: Extension attributes – additional context metadata keyed by attribute name.
	Extensions    map[string]string `protobuf:"bytes,10,rep,name=extensions,proto3" json:"extensions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_proto_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Message) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Message) GetSpecversion() string {
	if x != nil {
		return x.Specversion
	}
	return ""
}

func (x *Message) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Message) GetDatacontenttype() string {
	if x != nil && x.Datacontenttype != nil {
		return *x.Datacontenttype
	}
	return ""
}

func (x *Message) GetDataschema() string {
	if x != nil && x.Dataschema != nil {
		return *x.Dataschema
	}
	return ""
}

func (x *Message) GetSubject() string {
	if x != nil && x.Subject != nil {
		return *x.Subject
	}
	return ""
}

func (x *Message) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *Message) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Message) GetExtensions() map[string]string {
	if x != nil {
		return x.Extensions
	}
	return nil
}

// PublishResponse is returned after a message is successfully published.
type PublishResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishResponse) Reset() {
	*x = PublishResponse{}
	mi := &file_proto_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResponse) ProtoMessage() {}

func (x *PublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResponse.ProtoReflect.Descriptor instead.
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{1}
}

func (x *PublishResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// SubscribeRequest is sent by the client to subscribe to a stream of messages.
type SubscribeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional filter on the CloudEvent type attribute.
	TypeFilter string `protobuf:"bytes,1,opt,name=type_filter,json=typeFilter,proto3" json:"type_filter,omitempty"`
	// Optional filter on the CloudEvent source attribute.
	SourceFilter  string `protobuf:"bytes,2,opt,name=source_filter,json=sourceFilter,proto3" json:"source_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_proto_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{2}
}

func (x *SubscribeRequest) GetTypeFilter() string {
	if x != nil {
		return x.TypeFilter
	}
	return ""
}

func (x *SubscribeRequest) GetSourceFilter() string {
	if x != nil {
		return x.SourceFilter
	}
	return ""
}

var File_proto_message_proto protoreflect.FileDescriptor

const file_proto_message_proto_rawDesc = "" +
	"\n" +
	"\x13proto/message.proto\x12\x05munin\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe8\x03\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12 \n" +
	"\vspecversion\x18\x03 \x01(\tR\vspecversion\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12-\n" +
	"\x0fdatacontenttype\x18\x05 \x01(\tH\x00R\x0fdatacontenttype\x88\x01\x01\x12#\n" +
	"\n" +
	"dataschema\x18\x06 \x01(\tH\x01R\n" +
	"dataschema\x88\x01\x01\x12\x1d\n" +
	"\asubject\x18\a \x01(\tH\x02R\asubject\x88\x01\x01\x123\n" +
	"\x04time\x18\b \x01(\v2\x1a.google.protobuf.TimestampH\x03R\x04time\x88\x01\x01\x12\x17\n" +
	"\x04data\x18\t \x01(\fH\x04R\x04data\x88\x01\x01\x12>\n" +
	"\n" +
	"extensions\x18\n" +
	" \x03(\v2\x1e.munin.Message.ExtensionsEntryR\n" +
	"extensions\x1a=\n" +
	"\x0fExtensionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x12\n" +
	"\x10_datacontenttypeB\r\n" +
	"\v_dataschemaB\n" +
	"\n" +
	"\b_subjectB\a\n" +
	"\x05_timeB\a\n" +
	"\x05_data\"!\n" +
	"\x0fPublishResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"X\n" +
	"\x10SubscribeRequest\x12\x1f\n" +
	"\vtype_filter\x18\x01 \x01(\tR\n" +
	"typeFilter\x12#\n" +
	"\rsource_filter\x18\x02 \x01(\tR\fsourceFilter2}\n" +
	"\x0eMessageService\x123\n" +
	"\aPublish\x12\x0e.munin.Message\x1a\x16.munin.PublishResponse(\x01\x126\n" +
	"\tSubscribe\x12\x17.munin.SubscribeRequest\x1a\x0e.munin.Message0\x01B\"Z github.com/alexjoedt/munin/protob\x06proto3"

var (
	file_proto_message_proto_rawDescOnce sync.Once
	file_proto_message_proto_rawDescData []byte
)

func file_proto_message_proto_rawDescGZIP() []byte {
	file_proto_message_proto_rawDescOnce.Do(func() {
		file_proto_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_message_proto_rawDesc), len(file_proto_message_proto_rawDesc)))
	})
	return file_proto_message_proto_rawDescData
}

var file_proto_message_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_message_proto_goTypes = []any{
	(*Message)(nil),               // 0: munin.Message
	(*PublishResponse)(nil),       // 1: munin.PublishResponse
	(*SubscribeRequest)(nil),      // 2: munin.SubscribeRequest
	nil,                           // 3: munin.Message.ExtensionsEntry
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_proto_message_proto_depIdxs = []int32{
	4, // 0: munin.Message.time:type_name -> google.protobuf.Timestamp
	3, // 1: munin.Message.extensions:type_name -> munin.Message.ExtensionsEntry
	0, // 2: munin.MessageService.Publish:input_type -> munin.Message
	2, // 3: munin.MessageService.Subscribe:input_type -> munin.SubscribeRequest
	1, // 4: munin.MessageService.Publish:output_type -> munin.PublishResponse
	0, // 5: munin.MessageService.Subscribe:output_type -> munin.Message
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_message_proto_init() }
func file_proto_message_proto_init() {
	if File_proto_message_proto != nil {
		return
	}
	file_proto_message_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_message_proto_rawDesc), len(file_proto_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_message_proto_goTypes,
		DependencyIndexes: file_proto_message_proto_depIdxs,
		MessageInfos:      file_proto_message_proto_msgTypes,
	}.Build()
	File_proto_message_proto = out.File
	file_proto_message_proto_goTypes = nil
	file_proto_message_proto_depIdxs = nil
}
